version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/"
    schedule:
      interval: "weekly"
    groups:
      terraform-major-minor:
        update-types: ["major", "minor"]
      terraform-patch:
        update-types: ["patch"]
