apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
type: Opaque
stringData:
  host: "clickhouse.default.svc.cluster.local"
  port: "9000"
  database: "jackfruit"
  user: "PLACEHOLDER"
  password: "PLACEHOLDER"
