apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  host: "postgres.default.svc.cluster.local"
  port: "5432"
  user: "jackfruit"
  password: "PLACEHOLDER"
  database: "dagster"
  catalog-database: "jackfruit"
