apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  host: "PLACEHOLDER"
  port: "PLACEHOLDER"
  user: "PLACEHOLDER"
  password: "PLACEHOLDER"
  database: "dagster"
  catalog-database: "jackfruit"
  dsn: "PLACEHOLDER"
