apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  access-key: "PLACEHOLDER"
  secret-key: "PLACEHOLDER"
  bucket: "jackfruit-raw"
  endpoint: "https://s3.nl-ams.scw.cloud"
  region: "nl-ams"
