apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-logging
data:
  z_logging.xml: |
    <clickhouse>
      <logger>
        <level>information</level>
        <console>1</console>
        <log>/dev/null</log>
        <errorlog>/dev/null</errorlog>
      </logger>

      <query_log>
        <database>system</database>
        <table>query_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <ttl>event_date + INTERVAL 14 DAY DELETE</ttl>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </query_log>

      <text_log remove="1"/>
      <trace_log remove="1"/>
      <asynchronous_metric_log remove="1"/>
      <query_thread_log remove="1"/>
    </clickhouse>
