controller:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    annotations:
      service.beta.kubernetes.io/scw-loadbalancer-id: "nl-ams-1/e5b02632-2758-4052-b335-c54b3d48e6f8"
      service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"
      service.beta.kubernetes.io/scw-loadbalancer-protocol-http: "*"
      service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: "443:nl-ams-1/a07094f3-d4b7-49bb-a234-a49da289dcf5"
      service.beta.kubernetes.io/scw-loadbalancer-timeout-server: "35s"
      service.beta.kubernetes.io/scw-loadbalancer-timeout-client: "35s"
      service.beta.kubernetes.io/scw-loadbalancer-timeout-connect: "5s"
    targetPorts:
      https: http
  config:
    use-forwarded-headers: "true"
    proxy-read-timeout: "30"
    log-format-escape-json: "true"
    log-format-upstream: '{"time":"$time_iso8601","remote_addr":"$remote_addr","request_method":"$request_method","request_uri":"$request_uri","status":$status,"body_bytes_sent":$body_bytes_sent,"request_time":$request_time,"upstream_response_time":"$upstream_response_time","http_referer":"$http_referer","http_user_agent":"$http_user_agent"}'
