apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-daemon
  labels:
    app: dagster-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster-daemon
  template:
    metadata:
      labels:
        app: dagster-daemon
    spec:
      serviceAccountName: dagster
      containers:
        - name: dagster-daemon
          image: rg.nl-ams.scw.cloud/climacterium/pipeline-python:latest
          command: ["dagster-daemon", "run"]
          resources:
            requests:
              memory: "768Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: DAGSTER_HOME
              value: /opt/dagster/dagster_home
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: user
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: password
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: host
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: database
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-key
            - name: MINIO_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: endpoint
            - name: ADS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-api-keys
                  key: ads-api-key
            - name: MINIO_USE_SSL
              value: "true"
            - name: CATALOG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: CATALOG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: CATALOG_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: CATALOG_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: port
            - name: CATALOG_PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: catalog-database
          volumeMounts:
            - name: dagster-config
              mountPath: /opt/dagster/dagster_home/dagster.yaml
              subPath: dagster.yaml
            - name: dagster-artifacts
              mountPath: /tmp/dagster-artifacts
      volumes:
        - name: dagster-config
          configMap:
            name: dagster-config
        - name: dagster-artifacts
          emptyDir:
            sizeLimit: 256Mi
